#!/usr/bin/ruby
#usage: ctouch_touch_inner.rb [<] ctouch_touch.js > ctouch/ctouch_touch.js

#I need to use innerHTML to handle linebreak.

print <<EOM
//generated by ctouch_touch_inner.rb
var s=document.createElement('script');
s.type='text/javascript';
s.id='ctouch_touch_js';
s.innerHTML="\\
EOM
while s=gets
	s.chomp!
	s.gsub!("\"","'")
	puts s+"\\n\\"
end

print <<EOM
";
document.documentElement.appendChild(s);
EOM
