#!/usr/bin/perl
#usage: ctouch_touch_inner.pl [<] ctouch_touch.js > ctouch/ctouch_touch.js
use strict;
use warnings;

#I need to use innerHTML to handle linebreak.

print <<EOM;
//generated by ctouch_touch_inner.pl
var s=document.createElement('script');
s.type='text/javascript';
s.id='ctouch_touch_js';
s.innerHTML="\\
EOM
while(<>){chomp($_);s/"/'/g;print $_."\\n\\\n";} # "\n\"+LF
print <<EOM;
";
document.documentElement.appendChild(s);
EOM
