chrome.webRequest.onBeforeRequest.addListener(
	function(details){
		return {redirectUrl: 'data:text/javascript;base64,JChmdW5jdGlvbigpewoJaWYodHlwZW9mICQuZm4uc25pcHBldCA9PSAiZnVuY3Rpb24iKXsKCQkkKCJwcmUuaGlnaGxpZ2h0IikuZWFjaChmdW5jdGlvbigpewoJCQl2YXIgbGFuZyA9ICQodGhpcykuYXR0cigibGFuZyIpOwoJCQl2YXIgbXlCb3ggPSAkKHRoaXMpLmF0dHIoImJveCIpOwoJCQl2YXIgbXlCb3hDb2xvciA9ICQodGhpcykuYXR0cigiYm94Q29sb3IiKTsKCQkJdmFyIG15Qm94RmlsbCA9ICQodGhpcykuYXR0cigiYm94RmlsbCIpOwoJCQl2YXIgbXlTaG93TnVtID0gJCh0aGlzKS5hdHRyKCJzaG93TnVtIikgPT0gImZhbHNlIiA/IGZhbHNlIDogdHJ1ZTsKCQkJaWYobGFuZyl7CgkJCQkkKHRoaXMpLnNuaXBwZXQobGFuZywge3N0eWxlOiJ0eXBpY2FsIixzaG93TnVtOm15U2hvd051bSwgbWVudTpmYWxzZSwgYm94Om15Qm94LCBib3hDb2xvcjpteUJveENvbG9yLCBib3hGaWxsOm15Qm94RmlsbH0pOwoJCQl9CgkJfSk7Cgl9CglpZih0eXBlb2YgQmVoYXZlID09ICJmdW5jdGlvbiIpewoJCW5ldyBCZWhhdmUoewoJCQl0ZXh0YXJlYTogCQlkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZWRpdG9yJyksCgkJCXJlcGxhY2VUYWI6IAl0cnVlLAoJCQlzb2Z0VGFiczogCQlmYWxzZSwKCQkJdGFiU2l6ZTogCQk0LAoJCQlhdXRvT3BlbjogCQl0cnVlLAoJCQlvdmVyd3JpdGU6IAkJdHJ1ZSwKCQkJYXV0b1N0cmlwOiAJCXRydWUsCgkJCWF1dG9JbmRlbnQ6IAl0cnVlCgkJfSk7Cgl9Cn0pOw=='};
	},
	{
		urls: ['https://codeiq.jp/js/syntax_highlight.js'],
		types: ['script']
	},
	['blocking']
);
